version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '12.0.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "Running the build job..."
            - run: npm install
            - run: CI=true npm run build
  test:
    executor:
      name: node/default
      tag: '12.0.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "Running the test job..."
            - run: npm install
            - run:  CI=true npm run test
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
